/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista projetos */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Cria projeto e a primeira iniciativa
         * @description RN-I1: projeto nasce com uma iniciativa, porque projeto sem iniciativa
         *     não é planejável.
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projeto com as iniciativas dele */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Exclui projeto
         * @description 409 se alguma iniciativa do projeto tiver alocação (§8).
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Altera projeto */
        patch: operations["update_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/initiatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista iniciativas
         * @description A query traz um valor por filtro; o `InitiativeFilter` é plural porque a
         *     porta do repositório é plural, e é aqui que o valor único é embrulhado.
         */
        get: operations["list_initiatives_api_v1_initiatives_get"];
        put?: never;
        /** Cria iniciativa */
        post: operations["create_initiative_api_v1_initiatives_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/initiatives/{initiative_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Iniciativa */
        get: operations["get_initiative_api_v1_initiatives__initiative_id__get"];
        put?: never;
        post?: never;
        /**
         * Exclui iniciativa
         * @description 409 se houver alocação, ou se for a última do projeto (§8). Nos dois
         *     casos o caminho é `CANCELLED`.
         */
        delete: operations["delete_initiative_api_v1_initiatives__initiative_id__delete"];
        options?: never;
        head?: never;
        /** Altera iniciativa */
        patch: operations["update_initiative_api_v1_initiatives__initiative_id__patch"];
        trace?: never;
    };
    "/api/v1/initiatives/{initiative_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transição manual de status
         * @description Só as transições manuais do §6.3. `BACKLOG <-> PLANNED` não passa por
         *     aqui: é efeito automático de ganhar ou perder alocação.
         */
        post: operations["change_status_api_v1_initiatives__initiative_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista membros */
        get: operations["list_members_api_v1_members_get"];
        put?: never;
        /** Cria membro */
        post: operations["create_member_api_v1_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Inativa membro
         * @description Soft delete: `is_active = false` (§6.4). Membro nunca é apagado —
         *     apagar reescreveria alocações passadas. Por isso a resposta é o membro
         *     inativado, e não 204: a UI atualiza a linha sem recarregar a lista.
         */
        delete: operations["deactivate_member_api_v1_members__member_id__delete"];
        options?: never;
        head?: never;
        /** Altera membro */
        patch: operations["update_member_api_v1_members__member_id__patch"];
        trace?: never;
    };
    "/api/v1/squads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista squads
         * @description Sem `sprint_number`, `members` vem vazio: a composição é por sprint
         *     (D11), e uma lista sem sprint seria mentira.
         */
        get: operations["list_squads_api_v1_squads_get"];
        put?: never;
        /** Cria squad */
        post: operations["create_squad_api_v1_squads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/squads/{squad_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Squad com a composição sprint por sprint */
        get: operations["get_squad_api_v1_squads__squad_id__get"];
        put?: never;
        post?: never;
        /**
         * Inativa squad
         * @description Soft delete: `is_active = false` (§8). As alocações que a squad tem no
         *     passado continuam de pé.
         */
        delete: operations["deactivate_squad_api_v1_squads__squad_id__delete"];
        options?: never;
        head?: never;
        /** Altera squad */
        patch: operations["update_squad_api_v1_squads__squad_id__patch"];
        trace?: never;
    };
    "/api/v1/squads/{squad_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composição por sprint */
        get: operations["list_memberships_api_v1_squads__squad_id__memberships_get"];
        /**
         * Substitui a composição no intervalo
         * @description Devolve a composição resultante, para a matriz da tela de time não
         *     recarregar o intervalo inteiro depois de cada edição.
         */
        put: operations["set_memberships_api_v1_squads__squad_id__memberships_put"];
        post?: never;
        /** Remove membros do intervalo */
        delete: operations["remove_memberships_api_v1_squads__squad_id__memberships_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista sprints
         * @description `from` e `to` são os nomes do §8; `from` é palavra reservada em Python,
         *     por isso o `alias`.
         */
        get: operations["list_sprints_api_v1_sprints_get"];
        put?: never;
        /** Cria sprint */
        post: operations["create_sprint_api_v1_sprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sprints/next/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Propõe a próxima sprint
         * @description RN10: próxima segunda depois do fim da anterior, `start + 11 dias`. É
         *     proposta, não criação — a tela deixa editar antes de confirmar.
         */
        get: operations["preview_next_sprint_api_v1_sprints_next_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sprints/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria a próxima sprint
         * @description Sem corpo: cria exatamente a proposta de `/next/preview` (§8).
         */
        post: operations["create_next_sprint_api_v1_sprints_next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista alocações
         * @description `member_id` aqui é o responsável **direto**. A alocação efetiva do §6.8
         *     — o que chega pelas squads do membro — é leitura de capacidade, e quem faz
         *     essa leitura é a grade.
         */
        get: operations["list_allocations_api_v1_allocations_get"];
        put?: never;
        /**
         * Aloca um intervalo de sprints
         * @description 200, e não 201: a operação é sobre um intervalo e o resultado é um
         *     relatório — o que foi criado, o que já existia e que sprint do intervalo
         *     não existe. Repetir o mesmo pedido não cria nada de novo (RN4).
         */
        post: operations["allocate_range_api_v1_allocations_post"];
        /**
         * Desaloca um intervalo de sprints
         * @description RN6: o corpo traz o intervalo. Intervalo sem alocação nenhuma não é
         *     erro, é operação vazia.
         */
        delete: operations["deallocate_range_api_v1_allocations_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/allocations/{allocation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Desaloca uma célula */
        delete: operations["deallocate_cell_api_v1_allocations__allocation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planning/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A grade de planejamento
         * @description Sem intervalo, a janela é o trimestre corrente (RN13).
         */
        get: operations["get_grid_api_v1_planning_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planning/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O backlog
         * @description Iniciativas em `BACKLOG`, sem as de projeto de reserva de capacidade.
         *     `DEPRIORITIZED` não aparece aqui — é filtro da tela de projetos (§8).
         */
        get: operations["get_backlog_api_v1_planning_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista alertas
         * @description Sem intervalo, a janela é da sprint atual (RN12) até a última
         *     cadastrada. Os silenciados saem da lista mas continuam contados em
         *     `muted_count`, que é o contador expansível do painel.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Silencia alerta
         * @description O `fingerprint` vem calculado pelo domínio e ancorado no sujeito mais a
         *     sprint. É por isso que entrar uma terceira iniciativa na mesma sprint não
         *     desfaz o silenciamento (cenário G do §13.1).
         */
        post: operations["mute_alert_api_v1_alerts_mute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/mute/{mute_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reativa alerta silenciado */
        delete: operations["unmute_alert_api_v1_alerts_mute__mute_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exporta o snapshot
         * @description Escreve os arquivos do §9 em `SNAPSHOT_DIR` e devolve os caminhos.
         */
        post: operations["export_snapshot_api_v1_snapshots_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaura o banco a partir de um snapshot
         * @description Modo `replace` apenas: apaga e recria, na transação da requisição.
         *
         *     Sem `confirm=true` nada é lido nem apagado — a recusa vem antes de o
         *     reader abrir a pasta.
         */
        post: operations["import_snapshot_api_v1_snapshots_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertOut
         * @description Alerta calculado. `mute_id` é o que o botão "Reativar" usa (§7.3).
         */
        AlertOut: {
            type: components["schemas"]["AlertType"];
            severity: components["schemas"]["Severity"];
            /** Sprint Number */
            sprint_number: number;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Entity Refs */
            entity_refs: components["schemas"]["EntityRefOut"][];
            /** Message */
            message: string;
            /** Fingerprint */
            fingerprint: string;
            /** Is Muted */
            is_muted: boolean;
            /** Mute Id */
            mute_id: string | null;
            /** Mute Reason */
            mute_reason: string | null;
        };
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "SQUAD_OVERLOADED" | "MEMBER_CONFLICT" | "MEMBER_IDLE" | "EMPTY_SQUAD";
        /**
         * AlertsOut
         * @description `muted_count` alimenta o contador expansível do painel (§7.3).
         */
        AlertsOut: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Muted Count */
            muted_count: number;
        };
        /**
         * AllocateRangeIn
         * @description `POST /allocations` (§8). Um responsável, nunca dois.
         *
         *     Mandar squad e membro juntos é `AMBIGUOUS_ASSIGNEE`, e mandar nenhum é
         *     `ASSIGNEE_REQUIRED`: a invariante é do domínio (`Assignee.from_ids`), não
         *     do schema, para que a CLI da Fase 5 não precise reimplementá-la.
         */
        AllocateRangeIn: {
            /**
             * Initiative Id
             * Format: uuid
             */
            initiative_id: string;
            /** From Sprint Number */
            from_sprint_number: number;
            /** To Sprint Number */
            to_sprint_number: number;
            /** Squad Id */
            squad_id?: string | null;
            /** Member Id */
            member_id?: string | null;
        };
        /**
         * AllocationCellOut
         * @description Uma célula tocada pela operação: a alocação e a sprint em que caiu.
         */
        AllocationCellOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sprint Number */
            sprint_number: number;
        };
        /**
         * AllocationOut
         * @description Uma linha de `GET /allocations`.
         */
        AllocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Initiative Id
             * Format: uuid
             */
            initiative_id: string;
            /**
             * Sprint Id
             * Format: uuid
             */
            sprint_id: string;
            /** Sprint Number */
            sprint_number: number;
            /** Squad Id */
            squad_id: string | null;
            /** Member Id */
            member_id: string | null;
        };
        /**
         * AllocationResultOut
         * @description Resposta de `POST /allocations` (§8).
         *
         *     `missing_sprint_numbers` é o relatório da alocação **parcial**: sprint que
         *     não existe no intervalo não derruba a operação inteira.
         *
         *     `alerts` é o **estado atual** dos alertas das sprints tocadas, não um diff,
         *     e inclui os silenciados com `is_muted: true` — para a UI dizer "já
         *     silenciado" em vez de gritar de novo.
         */
        AllocationResultOut: {
            /** Created */
            created: components["schemas"]["AllocationCellOut"][];
            /** Already Existed */
            already_existed: components["schemas"]["AllocationCellOut"][];
            /** Missing Sprint Numbers */
            missing_sprint_numbers: number[];
            initiative_status: components["schemas"]["InitiativeStatus"];
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
        };
        /**
         * AssigneeKind
         * @description Minúsculo porque é o valor que viaja no JSON (`assignee.kind`, §8).
         * @enum {string}
         */
        AssigneeKind: "squad" | "member";
        /** BacklogItemOut */
        BacklogItemOut: {
            initiative: components["schemas"]["InitiativeOut"];
            project: components["schemas"]["BacklogProjectOut"];
        };
        /**
         * BacklogOrder
         * @description Valores de `?order_by=` (§8), minúsculos porque viajam na query string.
         * @enum {string}
         */
        BacklogOrder: "priority" | "size" | "entered_at";
        /** BacklogOut */
        BacklogOut: {
            /** Items */
            items: components["schemas"]["BacklogItemOut"][];
            summary: components["schemas"]["BacklogSummaryOut"];
        };
        /**
         * BacklogProjectOut
         * @description Sem `is_capacity_reserve`: o backlog já exclui esses projetos (§8).
         */
        BacklogProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /**
         * BacklogSummaryOut
         * @description `estimated_sprints_total` soma **só** quem tem estimativa (§8).
         */
        BacklogSummaryOut: {
            /** Count */
            count: number;
            /** Estimated Sprints Total */
            estimated_sprints_total: number;
            /** Items Without Estimate */
            items_without_estimate: number;
        };
        /**
         * DeallocateRangeIn
         * @description `DELETE /allocations` com o intervalo no corpo (RN6).
         */
        DeallocateRangeIn: {
            /**
             * Initiative Id
             * Format: uuid
             */
            initiative_id: string;
            /** From Sprint Number */
            from_sprint_number: number;
            /** To Sprint Number */
            to_sprint_number: number;
        };
        /**
         * DeallocationResultOut
         * @description Resposta dos dois `DELETE` de alocação: o que saiu, o status resultante
         *     e os alertas das sprints tocadas.
         */
        DeallocationResultOut: {
            /** Removed */
            removed: components["schemas"]["AllocationCellOut"][];
            initiative_status: components["schemas"]["InitiativeStatus"];
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
        };
        /**
         * EntityRefOut
         * @description Referência tipada, nunca UUID cru — a UI precisa do nome para o link.
         */
        EntityRefOut: {
            type: components["schemas"]["EntityRefType"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * EntityRefType
         * @description Minúsculo, como `assignee.kind`: é valor de JSON.
         * @enum {string}
         */
        EntityRefType: "project" | "initiative" | "squad" | "member";
        /**
         * ErrorBody
         * @description O corpo do erro do §8.
         *
         *     `code` é o contrato estável — é por ele que a UI decide a mensagem, não
         *     pelo texto. `details` carrega os dados que o aviso usa (qual sprint, qual
         *     projeto), sempre em primitivos.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
        };
        /**
         * ErrorEnvelope
         * @description `{ "error": { "code": ..., "message": ..., "details": {} } }` (§8).
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * GridAssigneeOut
         * @description `kind` é `"squad"` ou `"member"` (§8).
         */
        GridAssigneeOut: {
            kind: components["schemas"]["AssigneeKind"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * GridBarOut
         * @description Sprints contíguas do mesmo responsável, já consolidadas.
         *
         *     Uma pausa no meio gera duas barras. O front desenha barras, não células —
         *     é o que dá a cara de Gantt.
         */
        GridBarOut: {
            assignee: components["schemas"]["GridAssigneeOut"];
            /** From Sprint Number */
            from_sprint_number: number;
            /** To Sprint Number */
            to_sprint_number: number;
            /** Allocation Ids */
            allocation_ids: string[];
        };
        /** GridGroupOut */
        GridGroupOut: {
            project: components["schemas"]["GridProjectOut"];
            /** Rows */
            rows: components["schemas"]["GridRowOut"][];
        };
        /** GridInitiativeOut */
        GridInitiativeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Layer */
            layer: string | null;
            status: components["schemas"]["InitiativeStatus"];
            priority: components["schemas"]["Priority"];
        };
        /**
         * GridOut
         * @description `alerts_by_sprint` reporta a sprint **inteira**.
         *
         *     Os filtros de squad, membro e projeto não o afetam: o ícone no cabeçalho da
         *     coluna existe para não esconder justamente o conflito que se quer ver (§8).
         *     A chave é o número da sprint — no JSON ela sai como string, porque é chave
         *     de objeto.
         */
        GridOut: {
            /** Sprints */
            sprints: components["schemas"]["GridSprintOut"][];
            /** Groups */
            groups: components["schemas"]["GridGroupOut"][];
            /** Alerts By Sprint */
            alerts_by_sprint: {
                [key: string]: components["schemas"]["AlertType"][];
            };
        };
        /**
         * GridProjectOut
         * @description A cor vem resolvida: é o projeto que carrega a cor da grade (§8).
         */
        GridProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Color */
            color: string;
            /** Is Capacity Reserve */
            is_capacity_reserve: boolean;
        };
        /**
         * GridRowOut
         * @description Uma iniciativa é uma linha. Por RN8 as barras nunca se sobrepõem.
         */
        GridRowOut: {
            initiative: components["schemas"]["GridInitiativeOut"];
            /** Bars */
            bars: components["schemas"]["GridBarOut"][];
        };
        /** GridSprintOut */
        GridSprintOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Is Current */
            is_current: boolean;
        };
        /** InitiativeCreateIn */
        InitiativeCreateIn: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Name */
            name: string;
            /** Layer */
            layer?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** @default MEDIUM */
            priority: components["schemas"]["Priority"];
            /** Estimated Sprints */
            estimated_sprints?: number | null;
        };
        /** InitiativeOut */
        InitiativeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Name */
            name: string;
            /** Layer */
            layer: string | null;
            /** Description */
            description: string;
            priority: components["schemas"]["Priority"];
            /** Estimated Sprints */
            estimated_sprints: number | null;
            status: components["schemas"]["InitiativeStatus"];
            /**
             * Entered At
             * Format: date
             */
            entered_at: string;
        };
        /**
         * InitiativePatchIn
         * @description Sem `status` e sem `project_id`.
         *
         *     Status muda por `POST /initiatives/{id}/status`, que é a transição manual
         *     validada do §6.3. Mover iniciativa de projeto não está no spec.
         */
        InitiativePatchIn: {
            /** Name */
            name?: string;
            /** Layer */
            layer?: string | null;
            /** Description */
            description?: string;
            priority?: components["schemas"]["Priority"];
            /** Estimated Sprints */
            estimated_sprints?: number | null;
        };
        /**
         * InitiativeStatus
         * @enum {string}
         */
        InitiativeStatus: "BACKLOG" | "PLANNED" | "IN_PROGRESS" | "DEPRIORITIZED" | "DONE" | "CANCELLED";
        /**
         * InitiativeStatusIn
         * @description `POST /initiatives/{id}/status`: transição manual do §6.3.
         */
        InitiativeStatusIn: {
            status: components["schemas"]["InitiativeStatus"];
        };
        /** MemberCreateIn */
        MemberCreateIn: {
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /** MemberPatchIn */
        MemberPatchIn: {
            /** Name */
            name?: string;
            /** Short Name */
            short_name?: string;
            /** Role */
            role?: string;
            /** Is Active */
            is_active?: boolean;
        };
        /**
         * MuteAlertIn
         * @description Silenciar exige motivo em texto e é reversível (§7.3).
         */
        MuteAlertIn: {
            /** Fingerprint */
            fingerprint: string;
            alert_type: components["schemas"]["AlertType"];
            /** Reason */
            reason: string;
        };
        /** MutedAlertOut */
        MutedAlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            alert_type: components["schemas"]["AlertType"];
            /** Fingerprint */
            fingerprint: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "HIGH" | "MEDIUM" | "LOW";
        /**
         * ProjectCreateIn
         * @description `POST /projects` cria também a primeira iniciativa (RN-I1).
         */
        ProjectCreateIn: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Color */
            color?: string | null;
            /**
             * Is Capacity Reserve
             * @default false
             */
            is_capacity_reserve: boolean;
        };
        /**
         * ProjectDetailOut
         * @description `GET /projects/{id}` e a resposta de `POST /projects`: inclui as
         *     iniciativas (§8).
         */
        ProjectDetailOut: {
            project: components["schemas"]["ProjectOut"];
            /** Initiatives */
            initiatives: components["schemas"]["InitiativeOut"][];
        };
        /**
         * ProjectOut
         * @description `color` é o que está gravado, e pode ser nulo.
         *
         *     Quem edita precisa ver o campo vazio para saber que não escolheu cor; a
         *     grade e o backlog recebem a cor já resolvida (§10.2).
         */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Color */
            color: string | null;
            /** Is Capacity Reserve */
            is_capacity_reserve: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ProjectPatchIn
         * @description `color: null` limpa a cor; a **ausência** de `color` não mexe nela (§8).
         */
        ProjectPatchIn: {
            /** Name */
            name?: string;
            /** Description */
            description?: string;
            /** Color */
            color?: string | null;
            /** Is Capacity Reserve */
            is_capacity_reserve?: boolean;
            /** Is Active */
            is_active?: boolean;
        };
        /**
         * RemoveMembershipsIn
         * @description `DELETE /squads/{id}/memberships`. `member_ids` ausente remove todos.
         */
        RemoveMembershipsIn: {
            /** Sprint From */
            sprint_from: number;
            /** Sprint To */
            sprint_to: number;
            /** Member Ids */
            member_ids?: string[] | null;
        };
        /**
         * SetMembershipsIn
         * @description `PUT /squads/{id}/memberships`: **substitui** a composição no intervalo.
         *
         *     Lista vazia é operação válida e significa "ninguém nesta squad nestas
         *     sprints" — é como se esvazia a composição sem apagar a squad.
         */
        SetMembershipsIn: {
            /** Sprint From */
            sprint_from: number;
            /** Sprint To */
            sprint_to: number;
            /**
             * Member Ids
             * @default []
             */
            member_ids: string[];
        };
        /**
         * Severity
         * @description Viaja em inglês até a UI, que faz o mapa para o rótulo em português.
         * @enum {string}
         */
        Severity: "WARNING" | "INFO";
        /**
         * SnapshotCountsOut
         * @description Quantas linhas o snapshot carrega, por entidade.
         */
        SnapshotCountsOut: {
            /** Projects */
            projects: number;
            /** Initiatives */
            initiatives: number;
            /** Members */
            members: number;
            /** Squads */
            squads: number;
            /** Squad Memberships */
            squad_memberships: number;
            /** Sprints */
            sprints: number;
            /** Allocations */
            allocations: number;
            /** Muted Alerts */
            muted_alerts: number;
        };
        /**
         * SnapshotExportOut
         * @description §8: o export devolve os caminhos gerados.
         */
        SnapshotExportOut: {
            /** Paths */
            paths: string[];
            counts: components["schemas"]["SnapshotCountsOut"];
        };
        /** SnapshotImportIn */
        SnapshotImportIn: {
            /**
             * Path
             * Format: path
             */
            path: string;
            /** @default replace */
            mode: components["schemas"]["SnapshotMode"];
        };
        /** SnapshotImportOut */
        SnapshotImportOut: {
            /**
             * Path
             * Format: path
             */
            path: string;
            mode: components["schemas"]["SnapshotMode"];
            counts: components["schemas"]["SnapshotCountsOut"];
        };
        /**
         * SnapshotMode
         * @description Minúsculo porque viaja no JSON (`mode: "replace"`, §8).
         * @enum {string}
         */
        SnapshotMode: "replace";
        /**
         * SprintCompositionOut
         * @description Quem está na squad em **uma** sprint.
         */
        SprintCompositionOut: {
            /**
             * Sprint Id
             * Format: uuid
             */
            sprint_id: string;
            /** Sprint Number */
            sprint_number: number;
            /** Members */
            members: components["schemas"]["MemberOut"][];
        };
        /**
         * SprintCreateIn
         * @description `number` ausente continua a numeração da última cadastrada (RN10).
         */
        SprintCreateIn: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Number */
            number?: number | null;
        };
        /**
         * SprintOut
         * @description `is_current` é derivado do conjunto inteiro (RN12), não da sprint.
         */
        SprintOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Is Current */
            is_current: boolean;
        };
        /**
         * SprintProposalOut
         * @description `GET /sprints/next/preview`: editável antes de confirmar (RN10).
         */
        SprintProposalOut: {
            /** Number */
            number: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** SquadCreateIn */
        SquadCreateIn: {
            /** Name */
            name: string;
            /** Representative Member Id */
            representative_member_id?: string | null;
        };
        /**
         * SquadDetailOut
         * @description `GET /squads/{id}`: a squad e a composição sprint por sprint (§8).
         */
        SquadDetailOut: {
            squad: components["schemas"]["SquadOut"];
            /** Memberships */
            memberships: components["schemas"]["SprintCompositionOut"][];
        };
        /**
         * SquadOut
         * @description `members` só vem preenchido quando `GET /squads` recebe `sprint_number`.
         *
         *     Sem a sprint pedida não existe "os membros da squad": a composição é por
         *     sprint (D11), e uma lista sem sprint seria mentira.
         */
        SquadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Representative Member Id */
            representative_member_id: string | null;
            /** Is Active */
            is_active: boolean;
            /** Sprint Number */
            sprint_number?: number | null;
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["MemberOut"][];
        };
        /** SquadPatchIn */
        SquadPatchIn: {
            /** Name */
            name?: string;
            /** Representative Member Id */
            representative_member_id?: string | null;
            /** Is Active */
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                active?: boolean | null;
                /** @description Busca por nome */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_initiatives_api_v1_initiatives_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: components["schemas"]["InitiativeStatus"] | null;
                priority?: components["schemas"]["Priority"] | null;
                layer?: string | null;
                /** @description Busca por nome */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_initiative_api_v1_initiatives_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiativeCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_initiative_api_v1_initiatives__initiative_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                initiative_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_initiative_api_v1_initiatives__initiative_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                initiative_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_initiative_api_v1_initiatives__initiative_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                initiative_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiativePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    change_status_api_v1_initiatives__initiative_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                initiative_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiativeStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiativeOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_members_api_v1_members_get: {
        parameters: {
            query?: {
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_member_api_v1_members_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deactivate_member_api_v1_members__member_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_member_api_v1_members__member_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_squads_api_v1_squads_get: {
        parameters: {
            query?: {
                active?: boolean | null;
                /** @description Expande a composição desta sprint */
                sprint_number?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_squad_api_v1_squads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SquadCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_squad_api_v1_squads__squad_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadDetailOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deactivate_squad_api_v1_squads__squad_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    update_squad_api_v1_squads__squad_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SquadPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_memberships_api_v1_squads__squad_id__memberships_get: {
        parameters: {
            query?: {
                sprint_from?: number | null;
                sprint_to?: number | null;
            };
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintCompositionOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    set_memberships_api_v1_squads__squad_id__memberships_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMembershipsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintCompositionOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    remove_memberships_api_v1_squads__squad_id__memberships_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                squad_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveMembershipsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintCompositionOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_sprints_api_v1_sprints_get: {
        parameters: {
            query?: {
                from?: number | null;
                to?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_sprint_api_v1_sprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SprintCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_next_sprint_api_v1_sprints_next_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintProposalOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_next_sprint_api_v1_sprints_next_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SprintOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_allocations_api_v1_allocations_get: {
        parameters: {
            query?: {
                sprint_from?: number | null;
                sprint_to?: number | null;
                squad_id?: string | null;
                member_id?: string | null;
                initiative_id?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationOut"][];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    allocate_range_api_v1_allocations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocateRangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationResultOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deallocate_range_api_v1_allocations_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeallocateRangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeallocationResultOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deallocate_cell_api_v1_allocations__allocation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                allocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeallocationResultOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_grid_api_v1_planning_grid_get: {
        parameters: {
            query?: {
                sprint_from?: number | null;
                sprint_to?: number | null;
                squad_id?: string | null;
                member_id?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GridOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_backlog_api_v1_planning_backlog_get: {
        parameters: {
            query?: {
                order_by?: components["schemas"]["BacklogOrder"];
                /** @description Inverte a ordem; nulos seguem por último */
                descending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                sprint_from?: number | null;
                sprint_to?: number | null;
                include_muted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    mute_alert_api_v1_alerts_mute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteAlertIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutedAlertOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    unmute_alert_api_v1_alerts_mute__mute_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_snapshot_api_v1_snapshots_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotExportOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    import_snapshot_api_v1_snapshots_import_post: {
        parameters: {
            query?: {
                /** @description Obrigatório: a importação apaga todos os dados (§8). */
                confirm?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotImportOut"];
                };
            };
            /** @description Erro de validação ou de regra */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
